### ISSUE TITLE
About the training code!!!

### ISSUE THREAD

**Issue by huihuimaimaiti** [btxviny/DUT-Video-Stabilization#1]
Thank you for your wonderful code! I am a student studying video stabilization. May I ask you for the training code? This will be very helpful to my study,  and I would appreciate it if you would like to publish the training code. Thanks again!

**Comment by btxviny** [comment]
Hi I'm glad if this code was of any help. This is not the official implementation of DUT. [This](https://github.com/Annbless/DUTCode/tree/main) is the official implementation, and unfortunately it does not include the training code . As for this repo, I  changed/simplified the inference code. Instead of the PWCNet for optical flow extraction (which needs custom cuda layers to be 'installed') I used RAFT which is available through torchvision and even generates better results. I also implement a different warping method inspired by [PCAFlow](https://ps.is.mpg.de/code/pca-flow-fast-approximate-optical-flow-computation).

**Comment by btxviny** [comment]
I have other repositories of different paper implementations including the training I used to reproduce their results.
With training code:
- [DMBVS](https://github.com/btxviny/Deep-Motion-Blind-Video-Stabilization)
- https://github.com/btxviny/Deep-Learning-Video-Stabilization-using-Optical-Flow
- [DIFRINT](https://github.com/btxviny/Video-Stabilization-through-Frame-Interpolation-using-DIFRINT)

Using a pretrained model:
-[CAIN](https://github.com/btxviny/Video-Stabilization-through-Frame-Interpolation-using-CAIN))

And here is a repo that includes various non deep stabilization methods, using trajectory optimization and filtering.
-https://github.com/btxviny/Trajectory-Optimization-and-Parametric-filtering-based-Video-Stabilization

**Comment by huihuimaimaiti** [comment]
Thank you for your patient and detailed reply. That means a lot!!!
